"build jar" throws a java.lang.NoClassDefFoundError because temp/META-INF contains the SpatialDriver file which is uses by the src/test directory.
This changeset adds the jts library to the classpath and fixes this issue.